The error System.ArgumentNullException: Value cannot be null. (Parameter 'source') inside Enumerable.Any confirms that the LINQ method is being called on a null list.
System.ArgumentNullException: Value cannot be null. (Parameter 'source') at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) at System.Linq.Enumerable.Any[TSource](IEnumerable1 source) at Shared.Models.Templates.StreamQualityTpl.Any() at Online.Controllers.Vibix.<>c__DisplayClass7_0.<<Video>b__0>d.MoveNext() --- End of stack trace from previous location --- at Shared.BaseController.InvkSemaphore(String key, RchClient rch, Func1 func) at Online.Controllers.Vibix.Video(String iframe) at lambda_method516(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Lampac.Engine.Middlewares.Module.InvokeAsync(HttpContext httpContext) in /opt/buildhome/repo/Lampac/Engine/Middlewares/Module.cs:line 87 at Lampac.Engine.Middlewares.Module.InvokeAsync(HttpContext httpContext) in /opt/buildhome/repo/Lampac/Engine/Middlewares/Module.cs:line 87 at Lampac.Engine.Middlewares.RequestStatistics.InvokeAsync(HttpContext context) in /opt/buildhome/repo/Lampac/Engine/Middlewares/RequestStatistics.cs:line 25 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context) at Lampac.Engine.Middlewares.Staticache.InvokeAsync(HttpContext httpContext) in /opt/buildhome/repo/Lampac/Engine/Middlewares/Staticache.cs:line 163 at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)